[build]
target = "thumbv7em-none-eabihf"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip RA4M1"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]
